timeout: 5
triggers:
  - name: git
    type: git_poller
    runs:
      - name: frdm_k64f
        container: linarotechnologies/genesis-sdk
        host-tag: amd64
        script: compile
        params:
          BOARD: frdm_k64f
          DEVICE_TYPE: frdm-k64f
          APP: tests/kernel/msgq/msgq_api
        triggers:
          - name: lava-test

  - name: lava-test
    type: lava
    runs:
      - name: frdm_k64f-test
        container: linarotechnologies/genesis-sdk
        host-tag: amd64
        script: lava-test

scripts:
  compile: |
    #!/bin/sh -ex
    . zephyr-env.sh
    cd $APP
    make
    cp outdir/$BOARD/zephyr.* /archive

  lava-test: |
    #!/bin/sh -ex
    cat >/archive/zephyr.yml <<EOF
    device_type: ${DEVICE_TYPE}
    job_name: ltd-jobserv ${H_PROJECT}/${H_BUILD}/${H_RUN}

    timeouts:
      job:
        minutes: 6
      action:
        minutes: 3
      wait-usb-device:
        seconds: 40

    priority: medium
    visibility: public

    actions:
    - deploy:
        timeout:
          minutes: 3
        to: tmpfs
        images:
            zephyr:
              url: $(generate-public-url ${H_TRIGGER_URL}zephyr.bin)

    - boot:
        method: cmsis-dap
        timeout:
          minutes: 3

    - test:
        monitors:
        - name: "Zephyr Unit Test Framework"
          start: tc_start()
          end: PROJECT EXECUTION
          pattern: (?P<result>(PASS|FAIL))\s-\s(?P<test_case_id>\w+)
          fixupdict:
            PASS: pass
            FAIL: fail
    EOF
    lava-submit /archive/zephyr.yml
