# An example to test a Python based project triggered by GitHub Pull Requests
# This can be tested under the simulator with:
#   ./simulator.py create \
#       -d ./examples/projects/persistent-volume.yml \
#       -t github \
#       -r unit-test \
#       -w /tmp/persistent-volume-simulator \
#       -p GH_OWNER=linaro-technologies-dev \
#       -p GH_REPO=ltd-ci-jobserv \
#       -p GH_PRNUM=35 \
#       -s githubtok=<your github personal access token>
timeout: 5
triggers:
  - name: github
    type: github_pr
    runs:
      - name: unit-test
        container: linarotechnologies/python-builder
        host-tag: amd64
        script: unit-test
        persistent-volumes:
          # The runner will create a local directory that's mounted into the
          # container at /var/cache-venv
          venv_cache-foo.12: /var/cache-venv
      - name: flake8
        container: linarotechnologies/python-builder
        host-tag: amd64
        script: flake8
    email:
      # this tells the JobServ to send an email when a build completes (ie
      # all the runs)
      users: 'andy.doan@linaro.org, tyler.baker@linaro.org'
      only_failures: True

scripts:
  flake8: |
    #!/bin/sh -ex
    pip3 install flake8
    flake8 --exclude=migrations/ ./

  unit-test: |
    #!/bin/sh -ex
    echo "This is persistent" >> /var/cache-venv/tmp.log
    ls -l /var/cache-venv/
